I-Logix-RPY-Archive version 8.8.0 Java 6107223
{ IClass 
	- _ownerHandle = { IHandle 
		- _m2Class = "ISubsystem";
		- _filename = "Default\\Default.sbs";
		- _subsystem = "";
		- _class = "";
		- _name = "Default";
		- _id = GUID dc273dcc-ec6a-4257-97c3-73c0831260b7;
	}
	- _id = GUID 4f561431-b6c3-4ba6-842e-24d9693d3050;
	- _myState = 8192;
	- _name = "Tachometer";
	- _modifiedTimeWeak = 11.28.2013::21:53:54;
	- _lastID = 7;
	- weakCGTime = 11.28.2013::21:53:54;
	- strongCGTime = 11.12.2013::22:21:21;
	- Operations = { IRPYRawContainer 
		- size = 10;
		- value = 
		{ IReception 
			- _id = GUID 3af0b03d-0bd2-4685-9c36-3a8dd43d8fa7;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "dispatcher_init_finished()";
				- _id = GUID e3a1f8e4-1479-4563-be40-3fe87ac31945;
			}
		}
		{ IReception 
			- _id = GUID 16a67708-be75-42cc-8a8b-b7f9a20d0f13;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "increase_p0_fan_speed()";
				- _id = GUID 91401b54-77a9-4901-9020-d49b9c6688ef;
			}
		}
		{ IReception 
			- _id = GUID 1f6395dd-248e-4284-8ebc-c9b60aaf1954;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "decrease_p0_fan_speed()";
				- _id = GUID 0930a230-0c44-4a9b-bca8-da0eedfcce09;
			}
		}
		{ IReception 
			- _id = GUID 63cff166-16e0-4c52-9abd-06c1f48cd341;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "increase_p_min_fan_speed()";
				- _id = GUID eb2cb9e8-4abc-4cc1-9849-c434037384fb;
			}
		}
		{ IReception 
			- _id = GUID 95202391-7a50-4085-9841-95b2a21d33ca;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "decrease_p_min_fan_speed()";
				- _id = GUID 00d073f8-6fdf-4bb0-8bc4-06db225f385c;
			}
		}
		{ IReception 
			- _id = GUID 21b3c601-c78c-4d3b-a193-24bdb0e1150f;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "update_parameter_display()";
				- _id = GUID cb8a5c1f-7a80-48ce-b9e2-b94f161716e6;
			}
		}
		{ IReception 
			- _id = GUID 16841808-e3b9-4051-bd6f-b8cee2c0e2c9;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "start_fan()";
				- _id = GUID 8265e2bf-b39c-4a7a-8bcb-20391ec3605c;
			}
		}
		{ IReception 
			- _id = GUID e2ed6f8f-7f09-4ee0-962b-8baf70239404;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "stop_fan()";
				- _id = GUID b9fd31d7-a69f-4d5d-be37-ad96377cb7f2;
			}
		}
		{ IReception 
			- _id = GUID 8db553d8-d941-48fb-b16b-9b819f85b8c6;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "fan_set_min_speed()";
				- _id = GUID 09fc8817-473b-4c7a-bba4-3630ee6cfa3b;
			}
		}
		{ IReception 
			- _id = GUID 367a6135-5984-495d-952b-1edd4e1562d2;
			- _myState = 8192;
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _event = { IHandle 
				- _m2Class = "IEvent";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "fan_set_normal_speed()";
				- _id = GUID ebb456ef-27f0-4ae1-8ff8-78acabcf358c;
			}
		}
	}
	- Attrs = { IRPYRawContainer 
		- size = 6;
		- value = 
		{ IAttribute 
			- _id = GUID b67f8d3d-85f3-4168-b32a-4cda760e77c0;
			- _myState = 8192;
			- _name = "speed";
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- ValueSpecifications = { IRPYRawContainer 
				- size = 1;
				- value = 
				{ ILiteralSpecification 
					- _id = GUID 0f015bda-b833-4791-9061-97110bd35b42;
					- _modifiedTimeWeak = 11.19.2013::22:12:39;
					- _value = "90";
				}
			}
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "int";
				- _id = GUID 3b5a0555-e8e5-4b86-9ea1-95ae819b6564;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
		{ IAttribute 
			- _id = GUID 7b4d45cc-d342-42ef-9699-f505ecec66a5;
			- _myState = 8192;
			- _name = "isOk";
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "boolean";
				- _id = GUID fee479b3-e691-4955-95c2-8ddd2dab234d;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
		{ IAttribute 
			- _id = GUID be3c6284-0199-4d24-b81b-1c3c08bb833b;
			- _myState = 8192;
			- _name = "minSpeed";
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- ValueSpecifications = { IRPYRawContainer 
				- size = 1;
				- value = 
				{ ILiteralSpecification 
					- _id = GUID 500be36a-6d97-48a2-84ca-8dbc210aa58d;
					- _modifiedTimeWeak = 11.19.2013::21:35:36;
					- _value = "5";
				}
			}
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "int";
				- _id = GUID 3b5a0555-e8e5-4b86-9ea1-95ae819b6564;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
		{ IAttribute 
			- _id = GUID b747a1e4-df40-4479-bc44-68a80d7fdd1c;
			- _myState = 8192;
			- _name = "current_speed";
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- ValueSpecifications = { IRPYRawContainer 
				- size = 1;
				- value = 
				{ ILiteralSpecification 
					- _id = GUID 13ce7395-ad23-42c8-a6f8-3e496342d8b2;
					- _modifiedTimeWeak = 11.19.2013::21:46:43;
					- _value = "0";
				}
			}
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "int";
				- _id = GUID 3b5a0555-e8e5-4b86-9ea1-95ae819b6564;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
		{ IAttribute 
			- _id = GUID 512d994f-c164-436c-ae56-b09a5db8a27b;
			- _myState = 8192;
			- _name = "fanOn";
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- ValueSpecifications = { IRPYRawContainer 
				- size = 1;
				- value = 
				{ ILiteralSpecification 
					- _id = GUID cce3c6b4-ab4a-4c12-bd06-9b8e4b2430a0;
					- _modifiedTimeWeak = 11.19.2013::23:34:49;
					- _value = "false";
				}
			}
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "boolean";
				- _id = GUID fee479b3-e691-4955-95c2-8ddd2dab234d;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
		{ IAttribute 
			- _id = GUID d8fe92de-0935-40a1-9633-150559bb2f0b;
			- _myState = 8192;
			- _name = "fullSpeedOn";
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- ValueSpecifications = { IRPYRawContainer 
				- size = 1;
				- value = 
				{ ILiteralSpecification 
					- _id = GUID a27c1536-97e3-473b-86c3-9876dbeb7701;
					- _modifiedTimeWeak = 11.19.2013::23:34:41;
					- _value = "false";
				}
			}
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "boolean";
				- _id = GUID fee479b3-e691-4955-95c2-8ddd2dab234d;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
	}
	- _multiplicity = "";
	- StateCharts = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IStateChart 
			- _id = GUID d28ac023-5269-474c-aaa6-a16fbcac3993;
			- _myState = 10240;
			- _name = "statechart_0";
			- _modifiedTimeWeak = 11.28.2013::21:53:54;
			- _lastID = 35;
			- weakCGTime = 11.28.2013::21:53:54;
			- strongCGTime = 11.12.2013::22:21:21;
			- _multiplicity = "";
			- _itsStateChart = { IHandle 
				- _m2Class = "";
			}
			- _classModifier = Unspecified;
			- _defNumber = 22;
			- Transitions = { IRPYRawContainer 
				- size = 21;
				- value = 
				{ IDefaultDrvdTrans 
					- _id = GUID 1d2d3972-ac22-4398-b6dd-341d8dbde7d8;
					- _myState = 2048;
					- _name = "defaulttransition_1";
					- _modifiedTimeWeak = 11.17.2013::22:41:36;
					- _errorStatus = ErrorItem;
					- _itsLabel = { ILabel 
						- _id = GUID 668f4ee3-0f26-4257-8dff-4dc4dacbc9a2;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _itsTrigger = NULL;
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID 9591052c-c810-46b0-ae4c-e8bd9ccce543;
					- _staticReaction = 0;
					- _itsSource = ;
					- _ofState = GUID 71faef44-3e53-4725-8849-2a4570be7044;
				}
				{ ITransition 
					- _id = GUID 7fc1ae40-67ab-4081-8d4e-80a08346ccf9;
					- _myState = 2048;
					- _name = "transition_12";
					- _modifiedTimeWeak = 11.17.2013::22:41:36;
					- _itsLabel = { ILabel 
						- _id = GUID 60c8508a-3e79-4cc5-b2d7-8e52db565896;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _itsTrigger = NULL;
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID 231ced60-31fa-44cf-ad42-41fb7bc0bf4b;
					- _staticReaction = 0;
					- _itsSource = GUID 9591052c-c810-46b0-ae4c-e8bd9ccce543;
				}
				{ ITransition 
					- _id = GUID c8f70ff0-854c-4abe-b68a-0db93535ba96;
					- _myState = 2048;
					- _name = "transition_7";
					- _modifiedTimeWeak = 11.19.2013::21:46:14;
					- _itsLabel = { ILabel 
						- _id = GUID f0f1b5d6-245a-437a-8798-c292870b02fb;
						- _modifiedTimeWeak = 11.19.2013::21:35:17;
						- _itsTrigger = { IInterfaceItemTrigger 
							- _id = GUID f9c22aa3-e41e-4683-ac92-48611d79b5f4;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "dispatcher_init_finished";
							- _info = "";
							- _itsInterfaceItem = { IHandle 
								- _m2Class = "IEvent";
								- _filename = "Default\\Default.sbs";
								- _subsystem = "Default";
								- _class = "";
								- _name = "dispatcher_init_finished()";
								- _id = GUID e3a1f8e4-1479-4563-be40-3fe87ac31945;
							}
						}
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID 1019276c-2fce-4ef2-96e7-c3ff7d73e851;
					- _staticReaction = 0;
					- _itsSource = GUID 231ced60-31fa-44cf-ad42-41fb7bc0bf4b;
				}
				{ IDefaultDrvdTrans 
					- _id = GUID 324004c5-cf5c-4538-8370-6578aef85230;
					- _myState = 2048;
					- _name = "defaulttransition_18";
					- _modifiedTimeWeak = 11.19.2013::21:39:3;
					- _itsLabel = { ILabel 
						- _id = GUID f63bcc36-ed5f-4a82-9d22-6484cd8f337c;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _itsTrigger = NULL;
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID daf8351b-cb69-4b63-a84e-ac29c7b9ca2a;
					- _staticReaction = 0;
					- _itsSource = ;
					- _ofState = GUID b6d3f03a-c49a-455e-8443-5f774f4cb973;
				}
				{ ITransition 
					- _id = GUID d7916c9f-0973-4cd7-9441-438ae66e9ace;
					- _myState = 2048;
					- _name = "transition_19";
					- _modifiedTimeWeak = 11.19.2013::21:39:36;
					- _itsLabel = { ILabel 
						- _id = GUID c765709f-4ab9-491b-990f-45c1d6506545;
						- _modifiedTimeWeak = 11.19.2013::21:39:36;
						- _itsTrigger = { IInterfaceItemTrigger 
							- _id = GUID d60077eb-cd2e-4759-a0cc-2ce71b621e2c;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "decrease_p0_fan_speed";
							- _info = "";
							- _itsInterfaceItem = { IHandle 
								- _m2Class = "IEvent";
								- _filename = "Default\\Default.sbs";
								- _subsystem = "Default";
								- _class = "";
								- _name = "decrease_p0_fan_speed()";
								- _id = GUID 0930a230-0c44-4a9b-bca8-da0eedfcce09;
							}
						}
						- _itsGuard = NULL;
						- _itsAction = { IAction 
							- _id = GUID dffccf51-8e98-4472-be7e-919cf8f6224f;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "if (speed == 99) speed = 95;
else if (speed > 34) speed -= 5;
else speed = 30;";
						}
					}
					- _itsTarget = GUID d25b1c47-19f5-4bf9-8173-87fdf5971d59;
					- _staticReaction = 0;
					- _itsSource = GUID daf8351b-cb69-4b63-a84e-ac29c7b9ca2a;
				}
				{ ITransition 
					- _id = GUID 6dea642d-1678-4165-bd05-107ef6ebe1e7;
					- _myState = 2048;
					- _name = "transition_20";
					- _modifiedTimeWeak = 11.19.2013::22:11:23;
					- _itsLabel = { ILabel 
						- _id = GUID 7882beeb-d05c-40e9-88c4-8b135838ea9c;
						- _modifiedTimeWeak = 11.19.2013::22:11:23;
						- _itsTrigger = NULL;
						- _itsGuard = NULL;
						- _itsAction = { IAction 
							- _id = GUID d5500c32-94ac-4495-a635-e74e4867c135;
							- _modifiedTimeWeak = 11.19.2013::22:11:23;
							- _body = "parent.gen(new update_parameter_display());";
						}
					}
					- _itsTarget = GUID daf8351b-cb69-4b63-a84e-ac29c7b9ca2a;
					- _staticReaction = 0;
					- _itsSource = GUID d25b1c47-19f5-4bf9-8173-87fdf5971d59;
				}
				{ ITransition 
					- _id = GUID 0fd544d7-141d-4d04-b8dc-0f0425d72138;
					- _myState = 2048;
					- _name = "transition_21";
					- _modifiedTimeWeak = 11.19.2013::21:40:49;
					- _itsLabel = { ILabel 
						- _id = GUID fdbf9394-0bc9-4e90-b821-dde3e862f764;
						- _modifiedTimeWeak = 11.19.2013::21:40:49;
						- _itsTrigger = { IInterfaceItemTrigger 
							- _id = GUID 20f16668-ad24-4b42-800d-6fbd1eb96157;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "decrease_p_min_fan_speed";
							- _info = "";
							- _itsInterfaceItem = { IHandle 
								- _m2Class = "IEvent";
								- _filename = "Default\\Default.sbs";
								- _subsystem = "Default";
								- _class = "";
								- _name = "decrease_p_min_fan_speed()";
								- _id = GUID 00d073f8-6fdf-4bb0-8bc4-06db225f385c;
							}
						}
						- _itsGuard = NULL;
						- _itsAction = { IAction 
							- _id = GUID c0f25eb8-940b-4a9b-9a4f-37eb14fc6fe7;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "  if (minSpeed > 5) --minSpeed;";
						}
					}
					- _itsTarget = GUID d25b1c47-19f5-4bf9-8173-87fdf5971d59;
					- _staticReaction = 0;
					- _itsSource = GUID daf8351b-cb69-4b63-a84e-ac29c7b9ca2a;
				}
				{ ITransition 
					- _id = GUID 2f069fc5-5dfb-4e8e-82bb-6efcda1d794d;
					- _myState = 2048;
					- _name = "transition_22";
					- _modifiedTimeWeak = 11.19.2013::21:41:20;
					- _itsLabel = { ILabel 
						- _id = GUID a39b0947-cec5-40e6-82b4-c8e30ebe777b;
						- _modifiedTimeWeak = 11.19.2013::21:41:20;
						- _itsTrigger = { IInterfaceItemTrigger 
							- _id = GUID 38833eae-a6f4-46c6-ab26-865ece267af8;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "increase_p_min_fan_speed";
							- _info = "";
							- _itsInterfaceItem = { IHandle 
								- _m2Class = "IEvent";
								- _filename = "Default\\Default.sbs";
								- _subsystem = "Default";
								- _class = "";
								- _name = "increase_p_min_fan_speed()";
								- _id = GUID eb2cb9e8-4abc-4cc1-9849-c434037384fb;
							}
						}
						- _itsGuard = NULL;
						- _itsAction = { IAction 
							- _id = GUID b2767410-8860-4936-8084-5a80f80cc8d2;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "if (minSpeed < 30) ++minSpeed;";
						}
					}
					- _itsTarget = GUID d25b1c47-19f5-4bf9-8173-87fdf5971d59;
					- _staticReaction = 0;
					- _itsSource = GUID daf8351b-cb69-4b63-a84e-ac29c7b9ca2a;
				}
				{ ITransition 
					- _id = GUID c4024a67-54d1-40ba-8b31-efe61f550f90;
					- _myState = 2048;
					- _name = "transition_23";
					- _modifiedTimeWeak = 11.21.2013::20:37:50;
					- _itsLabel = { ILabel 
						- _id = GUID 0d3a1f67-b567-4a49-8f59-34a575fedcfc;
						- _modifiedTimeWeak = 11.21.2013::20:37:50;
						- _itsTrigger = { IInterfaceItemTrigger 
							- _id = GUID a3e25e1d-3c8b-467c-bc02-27c71e29a2b2;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "increase_p0_fan_speed";
							- _info = "";
							- _itsInterfaceItem = { IHandle 
								- _m2Class = "IEvent";
								- _filename = "Default\\Default.sbs";
								- _subsystem = "Default";
								- _class = "";
								- _name = "increase_p0_fan_speed()";
								- _id = GUID 91401b54-77a9-4901-9020-d49b9c6688ef;
							}
						}
						- _itsGuard = NULL;
						- _itsAction = { IAction 
							- _id = GUID 238d76dd-a4c1-43ca-a565-09d889037bff;
							- _modifiedTimeWeak = 11.21.2013::20:37:50;
							- _body = "if (speed < 95) speed += 5; else speed = 99;          
if (parent.dataProvider != null) parent.dataProvider.changeFanSpeed(speed);";
						}
					}
					- _itsTarget = GUID d25b1c47-19f5-4bf9-8173-87fdf5971d59;
					- _staticReaction = 0;
					- _itsSource = GUID daf8351b-cb69-4b63-a84e-ac29c7b9ca2a;
				}
				{ ITransition 
					- _id = GUID 55a1cfe3-9dc8-44ab-816a-e87218ca631e;
					- _myState = 2048;
					- _name = "transition_24";
					- _modifiedTimeWeak = 11.19.2013::21:46:35;
					- _itsLabel = { ILabel 
						- _id = GUID 6ae315b3-da75-496b-ad44-7409a2c6f880;
						- _modifiedTimeWeak = 11.19.2013::21:46:35;
						- _itsTrigger = { ITimeout 
							- _id = GUID 63dfed83-7916-43fe-86d8-e449a0f6f6be;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "tm(2000)";
							- _info = "";
							- _time = "2000";
						}
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID 48f654ca-8705-4c73-8ec5-0cb817e9ccad;
					- _staticReaction = 0;
					- _itsSource = GUID 70477e78-3b2f-40d9-872d-d8fa907f2b0d;
				}
				{ IDefaultDrvdTrans 
					- _id = GUID e9c91462-bd80-4cce-b9f6-bf93d3a6299d;
					- _myState = 2048;
					- _name = "defaulttransition_25";
					- _modifiedTimeWeak = 11.19.2013::21:43:14;
					- _itsLabel = { ILabel 
						- _id = GUID 83d996e4-1c18-4872-a8e1-b5d32a9920f8;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _itsTrigger = NULL;
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID 70477e78-3b2f-40d9-872d-d8fa907f2b0d;
					- _staticReaction = 0;
					- _itsSource = ;
					- _ofState = GUID 74a2b65a-4180-480d-ace7-649c262ec8c0;
				}
				{ ITransition 
					- _id = GUID 99f469e4-f3d1-4fe8-adc6-78171d6c553d;
					- _myState = 2048;
					- _name = "transition_27";
					- _modifiedTimeWeak = 11.19.2013::21:43:27;
					- _itsLabel = { ILabel 
						- _id = GUID e6c3775e-fb34-4d28-9948-fe1535c113fa;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _itsTrigger = NULL;
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID b37a0078-39b6-473e-97c2-f42967d35372;
					- _staticReaction = 0;
					- _itsSource = GUID 48f654ca-8705-4c73-8ec5-0cb817e9ccad;
				}
				{ ITransition 
					- _id = GUID 7a23ad6f-78c9-499b-843b-e905c54589aa;
					- _myState = 2048;
					- _name = "transition_28";
					- _modifiedTimeWeak = 11.19.2013::21:44:20;
					- _itsLabel = { ILabel 
						- _id = GUID f95d0c44-6511-45de-b03b-21993fbf331c;
						- _modifiedTimeWeak = 11.19.2013::21:44:20;
						- _itsTrigger = NULL;
						- _itsGuard = { IGuard 
							- _id = GUID 69024614-462b-4a58-ba1d-b05f2b3f9e1f;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "isOk==false";
						}
						- _itsAction = NULL;
					}
					- _itsTarget = GUID 7cf336a1-5488-44a8-b059-6fa7e4392819;
					- _staticReaction = 0;
					- _itsSource = GUID b37a0078-39b6-473e-97c2-f42967d35372;
				}
				{ ITransition 
					- _id = GUID 085c970e-b045-4344-8251-dce031613599;
					- _myState = 2048;
					- _name = "transition_29";
					- _modifiedTimeWeak = 11.19.2013::21:47:6;
					- _itsLabel = { ILabel 
						- _id = GUID fd9a6814-77e4-4ee9-a30e-99a380f83321;
						- _modifiedTimeWeak = 11.19.2013::21:47:6;
						- _itsTrigger = NULL;
						- _itsGuard = { IGuard 
							- _id = GUID 4f1db5cc-5961-4b94-b43b-ee72ee01f5ca;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "isOk == true";
						}
						- _itsAction = NULL;
					}
					- _itsTarget = GUID 8f2c8973-c583-4eda-82c2-3bc801455484;
					- _staticReaction = 0;
					- _itsSource = GUID b37a0078-39b6-473e-97c2-f42967d35372;
				}
				{ ITransition 
					- _id = GUID 67fc41b1-f314-40b8-b6ee-7e9cca891ada;
					- _myState = 2048;
					- _name = "transition_30";
					- _modifiedTimeWeak = 11.19.2013::21:45:9;
					- _itsLabel = { ILabel 
						- _id = GUID 1b81d2f0-b7fe-463c-bad9-f273c79b8b87;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _itsTrigger = NULL;
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID 70477e78-3b2f-40d9-872d-d8fa907f2b0d;
					- _staticReaction = 0;
					- _itsSource = GUID 8f2c8973-c583-4eda-82c2-3bc801455484;
				}
				{ ITransition 
					- _id = GUID 71eef5cb-314c-4a17-b90f-702907403791;
					- _myState = 2048;
					- _name = "transition_31";
					- _modifiedTimeWeak = 11.19.2013::21:45:15;
					- _itsLabel = { ILabel 
						- _id = GUID dee32176-c389-4fe7-b108-088a0723f5ee;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _itsTrigger = NULL;
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID 70477e78-3b2f-40d9-872d-d8fa907f2b0d;
					- _staticReaction = 0;
					- _itsSource = GUID 7cf336a1-5488-44a8-b059-6fa7e4392819;
				}
				{ IDefaultDrvdTrans 
					- _id = GUID 7ae3a071-ef70-4398-ab29-30e4562fe902;
					- _myState = 2048;
					- _name = "defaulttransition_32";
					- _modifiedTimeWeak = 11.19.2013::23:30:29;
					- _itsLabel = { ILabel 
						- _id = GUID 87a76d77-f35d-4082-963b-5a07925f5a3f;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _itsTrigger = NULL;
						- _itsGuard = NULL;
						- _itsAction = NULL;
					}
					- _itsTarget = GUID ab58aa37-a300-4e19-988d-063853aca1ce;
					- _staticReaction = 0;
					- _itsSource = ;
					- _ofState = GUID cc4a836c-ceec-464c-a329-8d6074fd463d;
				}
				{ ITransition 
					- _id = GUID 5281803d-1311-4f53-84d1-3dd26e6c0204;
					- _myState = 2048;
					- _name = "transition_33";
					- _modifiedTimeWeak = 11.20.2013::9:3:45;
					- _itsLabel = { ILabel 
						- _id = GUID fec90016-0a00-4ec7-8b47-9e9e3a543711;
						- _modifiedTimeWeak = 11.20.2013::9:3:45;
						- _itsTrigger = { IInterfaceItemTrigger 
							- _id = GUID bb83341f-bfbb-45ce-9412-fcd32f4cb0df;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "start_fan";
							- _info = "";
							- _itsInterfaceItem = { IHandle 
								- _m2Class = "IEvent";
								- _filename = "Default\\Default.sbs";
								- _subsystem = "Default";
								- _class = "";
								- _name = "start_fan()";
								- _id = GUID 8265e2bf-b39c-4a7a-8bcb-20391ec3605c;
							}
						}
						- _itsGuard = NULL;
						- _itsAction = { IAction 
							- _id = GUID 6e207e89-8ebf-40e0-8a59-21f563782c23;
							- _modifiedTimeWeak = 11.20.2013::9:3:45;
							- _body = "fanOn = true;                
fullSpeedOn = true;";
						}
					}
					- _itsTarget = GUID cd53514a-f931-45c7-b5b7-977becb023c4;
					- _staticReaction = 0;
					- _itsSource = GUID ab58aa37-a300-4e19-988d-063853aca1ce;
				}
				{ ITransition 
					- _id = GUID 8a357026-d555-4fa2-a50f-840083f56c8f;
					- _myState = 2048;
					- _name = "transition_34";
					- _modifiedTimeWeak = 11.19.2013::23:46:33;
					- _itsLabel = { ILabel 
						- _id = GUID c3b38205-4f7c-4ec1-abca-61ea1f59098a;
						- _modifiedTimeWeak = 11.19.2013::23:46:33;
						- _itsTrigger = { IInterfaceItemTrigger 
							- _id = GUID 075beb2e-bb69-4ff1-814c-f7eea7fc1757;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "stop_fan";
							- _info = "";
							- _itsInterfaceItem = { IHandle 
								- _m2Class = "IEvent";
								- _filename = "Default\\Default.sbs";
								- _subsystem = "Default";
								- _class = "";
								- _name = "stop_fan()";
								- _id = GUID b9fd31d7-a69f-4d5d-be37-ad96377cb7f2;
							}
						}
						- _itsGuard = NULL;
						- _itsAction = { IAction 
							- _id = GUID d8366785-7c72-4882-be5f-900230f99de6;
							- _modifiedTimeWeak = 11.19.2013::23:46:33;
							- _body = "fanOn = false;";
						}
					}
					- _itsTarget = GUID ab58aa37-a300-4e19-988d-063853aca1ce;
					- _staticReaction = 0;
					- _itsSource = GUID cd53514a-f931-45c7-b5b7-977becb023c4;
				}
				{ ITransition 
					- _id = GUID c1df49c3-0851-4a09-a81d-8b6ce2c40b77;
					- _modifiedTimeWeak = 11.21.2013::20:59:32;
					- _itsLabel = { ILabel 
						- _id = GUID 2c6a075c-fdbf-4620-83ca-ed75f1c68122;
						- _modifiedTimeWeak = 11.21.2013::20:59:32;
						- _itsTrigger = { IInterfaceItemTrigger 
							- _id = GUID 7ce24d47-0376-4b9b-aba7-796b071d0946;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "fan_set_min_speed";
							- _info = "";
							- _itsInterfaceItem = { IHandle 
								- _m2Class = "IEvent";
								- _filename = "Default\\Default.sbs";
								- _subsystem = "Default";
								- _class = "";
								- _name = "fan_set_min_speed()";
								- _id = GUID 09fc8817-473b-4c7a-bba4-3630ee6cfa3b;
							}
						}
						- _itsGuard = NULL;
						- _itsAction = { IAction 
							- _id = GUID b26015ea-bd45-4e4a-ab77-a3bb2a8023d3;
							- _modifiedTimeWeak = 11.21.2013::20:59:32;
							- _body = "fullSpeedOn = false;       
if (parent.dataProvider != null) parent.dataProvider.changeFanSpeed(minSpeed);";
						}
					}
					- _itsTarget = GUID cd53514a-f931-45c7-b5b7-977becb023c4;
					- _staticReaction = 1;
					- _itsSource = GUID cd53514a-f931-45c7-b5b7-977becb023c4;
				}
				{ ITransition 
					- _id = GUID ad87b1c3-6bb2-450a-9807-6a979b4e6d12;
					- _modifiedTimeWeak = 11.21.2013::21:0:8;
					- _itsLabel = { ILabel 
						- _id = GUID c3626893-5862-4605-a8bf-0e7e32774b20;
						- _modifiedTimeWeak = 11.21.2013::21:0:8;
						- _itsTrigger = { IInterfaceItemTrigger 
							- _id = GUID 35ef461a-f948-4643-a9f7-997959962978;
							- _modifiedTimeWeak = 1.2.1990::0:0:0;
							- _body = "fan_set_normal_speed";
							- _info = "";
							- _itsInterfaceItem = { IHandle 
								- _m2Class = "IEvent";
								- _filename = "Default\\Default.sbs";
								- _subsystem = "Default";
								- _class = "";
								- _name = "fan_set_normal_speed()";
								- _id = GUID ebb456ef-27f0-4ae1-8ff8-78acabcf358c;
							}
						}
						- _itsGuard = NULL;
						- _itsAction = { IAction 
							- _id = GUID 6027e017-ba08-4b38-b9c8-ad42d242dc35;
							- _modifiedTimeWeak = 11.21.2013::21:0:8;
							- _body = "fullSpeedOn = true;  
if (parent.dataProvider != null) parent.dataProvider.changeFanSpeed(speed);";
						}
					}
					- _itsTarget = GUID cd53514a-f931-45c7-b5b7-977becb023c4;
					- _staticReaction = 1;
					- _itsSource = GUID cd53514a-f931-45c7-b5b7-977becb023c4;
				}
			}
			- Connectors = { IRPYRawContainer 
				- size = 1;
				- value = 
				{ IBranch 
					- _id = GUID b37a0078-39b6-473e-97c2-f42967d35372;
					- _name = "condition_26";
					- _modifiedTimeWeak = 11.19.2013::21:45:4;
					- _parent = GUID 74a2b65a-4180-480d-ace7-649c262ec8c0;
					- _connectorType = Condition;
				}
			}
			- States = { IRPYRawContainer 
				- size = 15;
				- value = 
				{ IState 
					- _id = GUID 71faef44-3e53-4725-8849-2a4570be7044;
					- _modifiedTimeWeak = 11.19.2013::21:46:3;
					- _parent = ;
					- _defaultTrans = GUID 1d2d3972-ac22-4398-b6dd-341d8dbde7d8;
				}
				{ IState 
					- _id = GUID 9591052c-c810-46b0-ae4c-e8bd9ccce543;
					- _name = "init";
					- _modifiedTimeWeak = 11.19.2013::21:35:27;
					- _parent = GUID 71faef44-3e53-4725-8849-2a4570be7044;
					- _defaultTrans = ;
				}
				{ IState 
					- _id = GUID 231ced60-31fa-44cf-ad42-41fb7bc0bf4b;
					- _myState = 2048;
					- _name = "sendaction_8";
					- _modifiedTimeWeak = 11.28.2013::21:53:54;
					- _parent = GUID 71faef44-3e53-4725-8849-2a4570be7044;
					- _stateType = EventState;
					- _defaultTrans = ;
					- _entryAction = { ISendAction 
						- _id = GUID a8e72bd6-fced-47e6-be60-334ad4c73943;
						- _myState = 4096;
						- _modifiedTimeWeak = 11.28.2013::21:53:54;
						- _body = "";
						- m_hTarget = { IHandle 
							- _m2Class = "IAssociationEnd";
							- _id = GUID 003d2dc1-e4b9-415f-a0cc-0ee0ab89f52d;
						}
						- m_hEvent = { IEventHandle 
							- _m2Class = "IEvent";
							- _filename = "Default\\Default.sbs";
							- _subsystem = "Default";
							- _class = "";
							- _name = "init_tachometer()";
							- _id = GUID 34e40cae-eea7-4d20-a340-b262b3533cb6;
						}
					}
				}
				{ IState 
					- _id = GUID 1019276c-2fce-4ef2-96e7-c3ff7d73e851;
					- _name = "running";
					- _modifiedTimeWeak = 11.19.2013::23:30:1;
					- _parent = GUID 71faef44-3e53-4725-8849-2a4570be7044;
					- _stateType = And;
					- _defaultTrans = ;
				}
				{ IState 
					- _id = GUID b6d3f03a-c49a-455e-8443-5f774f4cb973;
					- _myState = 2048;
					- _name = "state_11";
					- _modifiedTimeWeak = 11.19.2013::21:39:3;
					- _parent = GUID 1019276c-2fce-4ef2-96e7-c3ff7d73e851;
					- _defaultTrans = GUID 324004c5-cf5c-4538-8370-6578aef85230;
				}
				{ IState 
					- _id = GUID 74a2b65a-4180-480d-ace7-649c262ec8c0;
					- _myState = 2048;
					- _name = "state_12";
					- _modifiedTimeWeak = 11.19.2013::21:43:58;
					- _parent = GUID 1019276c-2fce-4ef2-96e7-c3ff7d73e851;
					- _defaultTrans = GUID e9c91462-bd80-4cce-b9f6-bf93d3a6299d;
				}
				{ IState 
					- _id = GUID daf8351b-cb69-4b63-a84e-ac29c7b9ca2a;
					- _name = "update_speed";
					- _modifiedTimeWeak = 11.19.2013::21:41:27;
					- _parent = GUID b6d3f03a-c49a-455e-8443-5f774f4cb973;
					- _defaultTrans = ;
				}
				{ IState 
					- _id = GUID d25b1c47-19f5-4bf9-8173-87fdf5971d59;
					- _name = "speed_updated";
					- _modifiedTimeWeak = 11.19.2013::21:41:27;
					- _parent = GUID b6d3f03a-c49a-455e-8443-5f774f4cb973;
					- _defaultTrans = ;
				}
				{ IState 
					- _id = GUID 70477e78-3b2f-40d9-872d-d8fa907f2b0d;
					- _name = "ready";
					- _modifiedTimeWeak = 11.19.2013::21:45:15;
					- _parent = GUID 74a2b65a-4180-480d-ace7-649c262ec8c0;
					- _defaultTrans = ;
					- _entryAction = { IAction 
						- _id = GUID 52e96d3f-cc7e-4f27-a2c2-79c680f37675;
						- _myState = 4096;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _body = "isOk = true;";
					}
				}
				{ IState 
					- _id = GUID 48f654ca-8705-4c73-8ec5-0cb817e9ccad;
					- _name = "check_current_value";
					- _modifiedTimeWeak = 11.21.2013::20:45:24;
					- _parent = GUID 74a2b65a-4180-480d-ace7-649c262ec8c0;
					- _defaultTrans = ;
					- _entryAction = { IAction 
						- _id = GUID aeb884db-0ca3-48b3-a5c9-8d2ad196b288;
						- _myState = 4096;
						- _modifiedTimeWeak = 11.21.2013::20:45:24;
						- _body = "if (parent.dataProvider != null) {
 	isOk = !parent.dataProvider.isFanBroken();
}";
					}
				}
				{ IState 
					- _id = GUID 8f2c8973-c583-4eda-82c2-3bc801455484;
					- _myState = 2048;
					- _name = "sendaction_17";
					- _modifiedTimeWeak = 11.28.2013::21:53:54;
					- _parent = GUID 74a2b65a-4180-480d-ace7-649c262ec8c0;
					- _stateType = EventState;
					- _defaultTrans = ;
					- _entryAction = { ISendAction 
						- _id = GUID 8f516479-5496-49f0-bbc7-f16b5dfdce2f;
						- _myState = 4096;
						- _modifiedTimeWeak = 11.28.2013::21:53:54;
						- _body = "";
						- m_hTarget = { IHandle 
							- _m2Class = "IAssociationEnd";
							- _id = GUID 003d2dc1-e4b9-415f-a0cc-0ee0ab89f52d;
						}
						- m_hEvent = { IEventHandle 
							- _m2Class = "IEvent";
							- _filename = "Default\\Default.sbs";
							- _subsystem = "Default";
							- _class = "";
							- _name = "updated_speed_value(int)";
							- _id = GUID 7dda2705-5b1f-4b06-8b7f-573b99c064d1;
						}
						- _ArgValCount = 1;
						{ IHandleWithData 
							- _m2Class = "IArgument";
							- _filename = "Default\\Default.sbs";
							- _subsystem = "Default";
							- _class = "";
							- _name = "updated_speed_value(int).0";
							- _id = GUID ee2bcb77-5f85-4361-93d6-cec1e70f5160;
							- _data = "current_speed";
						}
						
					}
				}
				{ IState 
					- _id = GUID 7cf336a1-5488-44a8-b059-6fa7e4392819;
					- _myState = 2048;
					- _name = "sendaction_18";
					- _modifiedTimeWeak = 11.28.2013::21:53:54;
					- _parent = GUID 74a2b65a-4180-480d-ace7-649c262ec8c0;
					- _stateType = EventState;
					- _defaultTrans = ;
					- _entryAction = { ISendAction 
						- _id = GUID 63cb0942-d5f6-4642-ae57-15df7a140eec;
						- _myState = 4096;
						- _modifiedTimeWeak = 11.28.2013::21:53:54;
						- _body = "";
						- m_hTarget = { IHandle 
							- _m2Class = "IAssociationEnd";
							- _id = GUID 003d2dc1-e4b9-415f-a0cc-0ee0ab89f52d;
						}
						- m_hEvent = { IEventHandle 
							- _m2Class = "IEvent";
							- _filename = "Default\\Default.sbs";
							- _subsystem = "Default";
							- _class = "";
							- _name = "error_speed()";
							- _id = GUID 14826a94-0bca-45b1-b557-57a7f6e2db0a;
						}
					}
				}
				{ IState 
					- _id = GUID cc4a836c-ceec-464c-a329-8d6074fd463d;
					- _myState = 2048;
					- _name = "state_19";
					- _modifiedTimeWeak = 11.19.2013::23:30:29;
					- _parent = GUID 1019276c-2fce-4ef2-96e7-c3ff7d73e851;
					- _defaultTrans = GUID 7ae3a071-ef70-4398-ab29-30e4562fe902;
				}
				{ IState 
					- _id = GUID ab58aa37-a300-4e19-988d-063853aca1ce;
					- _name = "fan_stopped";
					- _modifiedTimeWeak = 11.19.2013::23:42:11;
					- _parent = GUID cc4a836c-ceec-464c-a329-8d6074fd463d;
					- _defaultTrans = ;
					- _entryAction = { IAction 
						- _id = GUID a7cabb2a-5ad6-4dbb-a84f-db61b8e924f2;
						- _myState = 4096;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _body = "parent.gen(new update_fan_display());";
					}
				}
				{ IState 
					- _id = GUID cd53514a-f931-45c7-b5b7-977becb023c4;
					- _name = "fan_on";
					- _modifiedTimeWeak = 11.19.2013::23:42:6;
					- _parent = GUID cc4a836c-ceec-464c-a329-8d6074fd463d;
					- _defaultTrans = ;
					- _entryAction = { IAction 
						- _id = GUID fe85ba8c-0536-470b-b59f-e220c08a94e8;
						- _myState = 4096;
						- _modifiedTimeWeak = 1.2.1990::0:0:0;
						- _body = "parent.gen(new update_fan_display());";
					}
				}
			}
			- _version = 11.28.2013::22:53:54;
			- _baseVersion = 1.2.1990::0:0:0;
			- _diagram = GUID 8ecb8ec9-dbd6-48c2-a957-8b0c4f13442d;
			- Views = { IRPYRawContainer 
				- size = 1;
				- value = 
				{ IStateChartDiagram 
					- _id = GUID 8ecb8ec9-dbd6-48c2-a957-8b0c4f13442d;
					- _myState = 10240;
					- _properties = { IPropertyContainer 
						- Subjects = { IRPYRawContainer 
							- size = 1;
							- value = 
							{ IPropertySubject 
								- _Name = "Format";
								- Metaclasses = { IRPYRawContainer 
									- size = 6;
									- value = 
									{ IPropertyMetaclass 
										- _Name = "DanglingTransition";
										- Properties = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IProperty 
												- _Name = "Line.LineWidth";
												- _Value = "2";
												- _Type = Int;
											}
										}
									}
									{ IPropertyMetaclass 
										- _Name = "DefaultTransition";
										- Properties = { IRPYRawContainer 
											- size = 5;
											- value = 
											{ IProperty 
												- _Name = "Font.Font";
												- _Value = "Tahoma";
												- _Type = String;
											}
											{ IProperty 
												- _Name = "Font.FontColor";
												- _Value = "0,0,0";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Font.Size";
												- _Value = "8";
												- _Type = Int;
											}
											{ IProperty 
												- _Name = "Line.LineColor";
												- _Value = "128,128,128";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Line.LineWidth";
												- _Value = "1";
												- _Type = Int;
											}
										}
									}
									{ IPropertyMetaclass 
										- _Name = "SendAction";
										- Properties = { IRPYRawContainer 
											- size = 7;
											- value = 
											{ IProperty 
												- _Name = "DefaultSize";
												- _Value = "0,0,100,40";
												- _Type = String;
											}
											{ IProperty 
												- _Name = "Fill.FillColor";
												- _Value = "225,235,245";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Font.Font";
												- _Value = "Tahoma";
												- _Type = String;
											}
											{ IProperty 
												- _Name = "Font.Size";
												- _Value = "8";
												- _Type = Int;
											}
											{ IProperty 
												- _Name = "Line.LineColor";
												- _Value = "109,163,217";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Line.LineStyle";
												- _Value = "0";
												- _Type = Int;
											}
											{ IProperty 
												- _Name = "Line.LineWidth";
												- _Value = "1";
												- _Type = Int;
											}
										}
									}
									{ IPropertyMetaclass 
										- _Name = "State";
										- Properties = { IRPYRawContainer 
											- size = 7;
											- value = 
											{ IProperty 
												- _Name = "DefaultSize";
												- _Value = "0,0,96,60";
												- _Type = String;
											}
											{ IProperty 
												- _Name = "Fill.FillColor";
												- _Value = "255,255,255";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Font.Font";
												- _Value = "Tahoma";
												- _Type = String;
											}
											{ IProperty 
												- _Name = "Font.Size";
												- _Value = "8";
												- _Type = Int;
											}
											{ IProperty 
												- _Name = "Line.LineColor";
												- _Value = "109,163,217";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Line.LineStyle";
												- _Value = "0";
												- _Type = Int;
											}
											{ IProperty 
												- _Name = "Line.LineWidth";
												- _Value = "1";
												- _Type = Int;
											}
										}
									}
									{ IPropertyMetaclass 
										- _Name = "StateChartConditionConnector";
										- Properties = { IRPYRawContainer 
											- size = 5;
											- value = 
											{ IProperty 
												- _Name = "DefaultSize";
												- _Value = "0,0,25,23";
												- _Type = String;
											}
											{ IProperty 
												- _Name = "Fill.FillColor";
												- _Value = "170,206,242";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Line.LineColor";
												- _Value = "109,163,217";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Line.LineColor@Child.InnerSymbol";
												- _Value = "0,0,0";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Line.LineWidth";
												- _Value = "1";
												- _Type = Int;
											}
										}
									}
									{ IPropertyMetaclass 
										- _Name = "Transition";
										- Properties = { IRPYRawContainer 
											- size = 5;
											- value = 
											{ IProperty 
												- _Name = "Font.Font";
												- _Value = "Tahoma";
												- _Type = String;
											}
											{ IProperty 
												- _Name = "Font.FontColor";
												- _Value = "0,0,0";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Font.Size";
												- _Value = "8";
												- _Type = Int;
											}
											{ IProperty 
												- _Name = "Line.LineColor";
												- _Value = "128,128,128";
												- _Type = Color;
											}
											{ IProperty 
												- _Name = "Line.LineWidth";
												- _Value = "1";
												- _Type = Int;
											}
										}
									}
								}
							}
						}
					}
					- _name = "statechartdiagram_0";
					- _modifiedTimeWeak = 11.28.2013::21:53:51;
					- _lastModifiedTime = "11.28.2013::21:53:54";
					- _graphicChart = { CGIStateChart 
						- _id = GUID f6632df0-ed54-48e2-93fa-196c94e18c57;
						- m_type = 0;
						- m_pModelObject = { IHandle 
							- _m2Class = "IStateChart";
							- _id = GUID d28ac023-5269-474c-aaa6-a16fbcac3993;
						}
						- m_pParent = ;
						- m_name = { CGIText 
							- m_str = "";
							- m_style = "Arial" 10 0 0 0 1 ;
							- m_color = { IColor 
								- m_fgColor = 0;
								- m_bgColor = 0;
								- m_bgFlag = 0;
							}
							- m_position = 1 0 0  ;
							- m_nIdent = 0;
							- m_bImplicitSetRectPoints = 0;
							- m_nOrientationCtrlPt = 8;
						}
						- m_drawBehavior = 4096;
						- m_bIsPreferencesInitialized = 1;
						- elementList = 35;
						{ CGIState 
							- _id = GUID 377ba89a-e88a-42f2-9506-8f2b18b82eb6;
							- m_type = 5;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID 71faef44-3e53-4725-8849-2a4570be7044;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "ROOT";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 0;
							- m_bIsPreferencesInitialized = 0;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 0  0 0  0 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
							- m_moveAndLineTimeStamp = 1.2.1990::0:0:0;
						}
						{ CGITrans 
							- _id = GUID b492a37d-be3c-4964-8361-ee6f9323c420;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 29;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 1d2d3972-ac22-4398-b6dd-341d8dbde7d8;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID 377ba89a-e88a-42f2-9506-8f2b18b82eb6;
							- m_sourceType = 'F';
							- m_pTarget = GUID bbaf50be-ea40-4b91-900c-10b3388939a8;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 47 45 ;
							- m_TargetPort = 822 247 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGIState 
							- _id = GUID bbaf50be-ea40-4b91-900c-10b3388939a8;
							- m_type = 8;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID 9591052c-c810-46b0-ae4c-e8bd9ccce543;
							}
							- m_pParent = GUID 377ba89a-e88a-42f2-9506-8f2b18b82eb6;
							- m_name = { CGIText 
								- m_str = "init";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4104;
							- m_transform = 0.0875912 0 0 0.0566038 10 121 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  1096 1060  1096 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
							- m_moveAndLineTimeStamp = 1.2.1990::0:0:0;
						}
						{ CGIState 
							- _id = GUID 9d19a09e-9630-419c-b973-145263d17f11;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 2;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "";
														- _Type = Bool;
													}
												}
											}
										}
									}
									{ IPropertySubject 
										- _Name = "StatechartDiagram";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "SendAction";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowNotation";
														- _Value = "FullNotation";
														- _Type = Enum;
														- _ExtraTypeInfo = "Name,Label,FullNotation,Event";
													}
												}
											}
										}
									}
								}
							}
							- m_type = 205;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID 231ced60-31fa-44cf-ad42-41fb7bc0bf4b;
							}
							- m_pParent = GUID 377ba89a-e88a-42f2-9506-8f2b18b82eb6;
							- m_name = { CGIText 
								- m_str = "sendaction_8";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4096;
							- m_transform = 0.145985 0 0 0.0377358 186 73 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  685 1060  685 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
							- m_moveAndLineTimeStamp = 1.2.1990::0:0:0;
						}
						{ CGITrans 
							- _id = GUID cfc0095b-1b1f-4e91-b9dc-6d94342d641b;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 7fc1ae40-67ab-4081-8d4e-80a08346ccf9;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID bbaf50be-ea40-4b91-900c-10b3388939a8;
							- m_sourceType = 'F';
							- m_pTarget = GUID 9d19a09e-9630-419c-b973-145263d17f11;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 479 795 ;
							- m_TargetPort = 329 344 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID 7055e541-6d0c-4c1f-a96c-25745ac2227b;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID c8f70ff0-854c-4abe-b68a-0db93535ba96;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID 9d19a09e-9630-419c-b973-145263d17f11;
							- m_sourceType = 'F';
							- m_pTarget = GUID 3a8f2324-0453-463e-bd0b-6b228528d4e8;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "dispatcher_init_finished";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 4 -6 -9  172 -9  172 5  -6 5  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_transform = 1 0 0 1 276 104 ;
								- m_nHorizontalSpacing = -70;
								- m_nVerticalSpacing = 3;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 630 663 ;
							- m_TargetPort = 158 -70 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGIState 
							- _id = GUID 3a8f2324-0453-463e-bd0b-6b228528d4e8;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "FitBoxToItsTextuals";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 6;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID 1019276c-2fce-4ef2-96e7-c3ff7d73e851;
							}
							- m_pParent = GUID 377ba89a-e88a-42f2-9506-8f2b18b82eb6;
							- m_name = { CGIText 
								- m_str = "running";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4104;
							- m_transform = 1.24088 0 0 0.256604 51 230 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  1096 1060  1096 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 2;
							- andLinePoly = 2 799 0  799 1060  ;
							- andLinePoly = 2 475 0  475 1060  ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
							- m_moveAndLineTimeStamp = 11.20.2013::0:29:18;
						}
						{ CGIState 
							- _id = GUID 49654d9c-4ecf-48d3-8532-89af9fd30e1a;
							- m_type = 9;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID b6d3f03a-c49a-455e-8443-5f774f4cb973;
							}
							- m_pParent = GUID 3a8f2324-0453-463e-bd0b-6b228528d4e8;
							- m_name = { CGIText 
								- m_str = "state_11";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 475 0  475 1060  0 1060  0 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
							- m_pVirtualParent = GUID 3a8f2324-0453-463e-bd0b-6b228528d4e8;
						}
						{ CGIState 
							- _id = GUID bd92fa63-830d-4204-9f1f-195b94854420;
							- m_type = 9;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID 74a2b65a-4180-480d-ace7-649c262ec8c0;
							}
							- m_pParent = GUID 3a8f2324-0453-463e-bd0b-6b228528d4e8;
							- m_name = { CGIText 
								- m_str = "state_12";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 799 0  799 1060  475 1060  475 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
							- m_pVirtualParent = GUID 3a8f2324-0453-463e-bd0b-6b228528d4e8;
						}
						{ CGIState 
							- _id = GUID e41949ca-1705-4953-912f-b6b0b2de3a1c;
							- m_type = 8;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID daf8351b-cb69-4b63-a84e-ac29c7b9ca2a;
							}
							- m_pParent = GUID 49654d9c-4ecf-48d3-8532-89af9fd30e1a;
							- m_name = { CGIText 
								- m_str = "update_speed";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4104;
							- m_transform = 0.12015 0 0 0.220588 49 140 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  1096 1060  1096 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
						}
						{ CGIState 
							- _id = GUID 89a18600-0512-4d2a-ae66-553da5f10f78;
							- m_type = 8;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID d25b1c47-19f5-4bf9-8173-87fdf5971d59;
							}
							- m_pParent = GUID 49654d9c-4ecf-48d3-8532-89af9fd30e1a;
							- m_name = { CGIText 
								- m_str = "speed_updated";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4104;
							- m_transform = 0.12015 0 0 0.220588 221 577 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  1096 1060  1096 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
						}
						{ CGITrans 
							- _id = GUID 32a9fe13-9d47-433a-b75d-256ae57c1c32;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 29;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 324004c5-cf5c-4538-8370-6578aef85230;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID 49654d9c-4ecf-48d3-8532-89af9fd30e1a;
							- m_sourceType = 'F';
							- m_pTarget = GUID e41949ca-1705-4953-912f-b6b0b2de3a1c;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 27 39 ;
							- m_TargetPort = 57 265 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID 6a053b28-0c52-49a0-8d8b-51941d8522c7;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID d7916c9f-0973-4cd7-9441-438ae66e9ace;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID e41949ca-1705-4953-912f-b6b0b2de3a1c;
							- m_sourceType = 'F';
							- m_pTarget = GUID 89a18600-0512-4d2a-ae66-553da5f10f78;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "decrease_p0_fan_speed/if (speed == 99) speed = 95;
else if (speed > 34) speed -= 5;
else speed = 30;";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 4 -6 -9  278 -9  278 33  -6 33  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_transform = 1 0 0 1 414 580 ;
								- m_nHorizontalSpacing = -64;
								- m_nVerticalSpacing = -42;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 1005 742 ;
							- m_TargetPort = 434 477 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID ac848f7d-7f3e-42a4-9650-852554fa6190;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 6dea642d-1678-4165-bd05-107ef6ebe1e7;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID 89a18600-0512-4d2a-ae66-553da5f10f78;
							- m_sourceType = 'F';
							- m_pTarget = GUID e41949ca-1705-4953-912f-b6b0b2de3a1c;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "/parent.gen(new update_parameter_display());";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 206 1025 ;
							- m_TargetPort = 11 760 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID 86f5c803-5213-4982-9545-8c32e35a1a6b;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 0fd544d7-141d-4d04-b8dc-0f0425d72138;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID e41949ca-1705-4953-912f-b6b0b2de3a1c;
							- m_sourceType = 'F';
							- m_pTarget = GUID 89a18600-0512-4d2a-ae66-553da5f10f78;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "decrease_p_min_fan_speed/  if (minSpeed > 5) --minSpeed;";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 1005 1025 ;
							- m_TargetPort = 206 212 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID 2c085a0d-f68a-4fd2-bd3f-07f931ce9921;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 2f069fc5-5dfb-4e8e-82bb-6efcda1d794d;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID e41949ca-1705-4953-912f-b6b0b2de3a1c;
							- m_sourceType = 'F';
							- m_pTarget = GUID 89a18600-0512-4d2a-ae66-553da5f10f78;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "increase_p_min_fan_speed/if (minSpeed < 30) ++minSpeed;";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 776 1042 ;
							- m_TargetPort = 251 406 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID d3e6a04f-a57b-4483-92fa-f0e458ddde38;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID c4024a67-54d1-40ba-8b31-efe61f550f90;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID e41949ca-1705-4953-912f-b6b0b2de3a1c;
							- m_sourceType = 'F';
							- m_pTarget = GUID 89a18600-0512-4d2a-ae66-553da5f10f78;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "increase_p0_fan_speed/if (speed < 95) speed += 5; else speed = 99;          
if (parent.dataProvider != null) parent.dataProvider.changeFanSpeed(speed);";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 582 1007 ;
							- m_TargetPort = 148 707 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGIState 
							- _id = GUID 2eb30135-6df0-4805-a082-7a3547c282d7;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "StatechartDiagram";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "State";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowReactions";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 8;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID 70477e78-3b2f-40d9-872d-d8fa907f2b0d;
							}
							- m_pParent = GUID bd92fa63-830d-4204-9f1f-195b94854420;
							- m_name = { CGIText 
								- m_str = "ready";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4104;
							- m_transform = 0.0824742 0 0 0.220588 545 148 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  1096 1060  1096 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- frameset = "<frameset rows=50%,50%>
<frame name=ReactionsCompartment>
<frame name=StructureCompartment>";
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
						}
						{ CGIState 
							- _id = GUID a1eb5aa9-d691-4960-b618-524c21551287;
							- m_type = 8;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID 48f654ca-8705-4c73-8ec5-0cb817e9ccad;
							}
							- m_pParent = GUID bd92fa63-830d-4204-9f1f-195b94854420;
							- m_name = { CGIText 
								- m_str = "check_current_value";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4104;
							- m_transform = 0.0824742 0 0 0.220588 678 281 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  1096 1060  1096 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
						}
						{ CGITrans 
							- _id = GUID 02023e0a-af44-49a4-ab1a-d8a2042a3bc6;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 55a1cfe3-9dc8-44ab-816a-e87218ca631e;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID 2eb30135-6df0-4805-a082-7a3547c282d7;
							- m_sourceType = 'F';
							- m_pTarget = GUID a1eb5aa9-d691-4960-b618-524c21551287;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "tm(2000)";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 1039 477 ;
							- m_TargetPort = 320 88 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID ddac36d5-1907-43c9-9395-de02434e17ba;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 29;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID e9c91462-bd80-4cce-b9f6-bf93d3a6299d;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID bd92fa63-830d-4204-9f1f-195b94854420;
							- m_sourceType = 'F';
							- m_pTarget = GUID 2eb30135-6df0-4805-a082-7a3547c282d7;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 516 47 ;
							- m_TargetPort = 9 477 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGIConnector 
							- _id = GUID b46b3976-c67b-430a-bd17-468c54003678;
							- m_type = 42;
							- m_pModelObject = { IHandle 
								- _m2Class = "IBranch";
								- _id = GUID b37a0078-39b6-473e-97c2-f42967d35372;
							}
							- m_pParent = GUID bd92fa63-830d-4204-9f1f-195b94854420;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 0;
							- m_transform = 0.805882 0 0 3.58529 696 783 ;
							- m_bIsPreferencesInitialized = 1;
							- m_position = 4 0 0  0 25  25 25  25 0  ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_SubType = 0;
						}
						{ CGITrans 
							- _id = GUID edeff2f8-e765-40c7-81ee-51cc741e6d38;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 99f469e4-f3d1-4fe8-adc6-78171d6c553d;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID a1eb5aa9-d691-4960-b618-524c21551287;
							- m_sourceType = 'F';
							- m_pTarget = GUID b46b3976-c67b-430a-bd17-468c54003678;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 160 972 ;
							- m_TargetPort = 18 15 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGIState 
							- _id = GUID 20150c74-4247-40f8-a2a1-6b6583caea66;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 2;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "";
														- _Type = Bool;
													}
												}
											}
										}
									}
									{ IPropertySubject 
										- _Name = "StatechartDiagram";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "SendAction";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowNotation";
														- _Value = "FullNotation";
														- _Type = Enum;
														- _ExtraTypeInfo = "Name,Label,FullNotation,Event";
													}
												}
											}
										}
									}
								}
							}
							- m_type = 205;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID 8f2c8973-c583-4eda-82c2-3bc801455484;
							}
							- m_pParent = GUID bd92fa63-830d-4204-9f1f-195b94854420;
							- m_name = { CGIText 
								- m_str = "sendaction_17";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4096;
							- m_transform = 0.137457 0 0 0.147059 526 468 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  685 1060  685 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
						}
						{ CGIState 
							- _id = GUID f60c3e77-37af-41e2-aa97-8dfeb57e19e3;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 2;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "";
														- _Type = Bool;
													}
												}
											}
										}
									}
									{ IPropertySubject 
										- _Name = "StatechartDiagram";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "SendAction";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowNotation";
														- _Value = "FullNotation";
														- _Type = Enum;
														- _ExtraTypeInfo = "Name,Label,FullNotation,Event";
													}
												}
											}
										}
									}
								}
							}
							- m_type = 205;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID 7cf336a1-5488-44a8-b059-6fa7e4392819;
							}
							- m_pParent = GUID bd92fa63-830d-4204-9f1f-195b94854420;
							- m_name = { CGIText 
								- m_str = "sendaction_18";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4096;
							- m_transform = 0.137457 0 0 0.147059 484 740 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  685 1060  685 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
						}
						{ CGITrans 
							- _id = GUID 1a3f3c48-26d5-493b-bf91-ed2dd16a7005;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 7a23ad6f-78c9-499b-843b-e905c54589aa;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID b46b3976-c67b-430a-bd17-468c54003678;
							- m_sourceType = 'F';
							- m_pTarget = GUID f60c3e77-37af-41e2-aa97-8dfeb57e19e3;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "[isOk==false]";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 8 15 ;
							- m_TargetPort = 623 610 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID 3eb1eaf3-4aca-42a8-bba5-495141e3c282;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 085c970e-b045-4344-8251-dce031613599;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID b46b3976-c67b-430a-bd17-468c54003678;
							- m_sourceType = 'F';
							- m_pTarget = GUID 20150c74-4247-40f8-a2a1-6b6583caea66;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "[isOk == true]";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 15 15 ;
							- m_TargetPort = 562 477 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID 42b2c92d-1044-45d5-bb0a-56dab6a89c55;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 67fc41b1-f314-40b8-b6ee-7e9cca891ada;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID 20150c74-4247-40f8-a2a1-6b6583caea66;
							- m_sourceType = 'F';
							- m_pTarget = GUID 2eb30135-6df0-4805-a082-7a3547c282d7;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 199 186 ;
							- m_TargetPort = 11 795 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID 4b4e13d3-7ad7-4c21-b1c2-cb96bb8038e3;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 71eef5cb-314c-4a17-b90f-702907403791;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID f60c3e77-37af-41e2-aa97-8dfeb57e19e3;
							- m_sourceType = 'F';
							- m_pTarget = GUID 2eb30135-6df0-4805-a082-7a3547c282d7;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 206 477 ;
							- m_TargetPort = 69 601 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGIState 
							- _id = GUID 7c6c8a23-3037-410e-a357-eaf3e1d2abab;
							- m_type = 9;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID cc4a836c-ceec-464c-a329-8d6074fd463d;
							}
							- m_pParent = GUID 3a8f2324-0453-463e-bd0b-6b228528d4e8;
							- m_name = { CGIText 
								- m_str = "state_19";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 799 0  799 1060  1096 1060  1096 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
							- m_pVirtualParent = GUID bd92fa63-830d-4204-9f1f-195b94854420;
						}
						{ CGIState 
							- _id = GUID e6c8cfac-cc12-48b8-aea3-96be39526d6f;
							- m_type = 8;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID ab58aa37-a300-4e19-988d-063853aca1ce;
							}
							- m_pParent = GUID 7c6c8a23-3037-410e-a357-eaf3e1d2abab;
							- m_name = { CGIText 
								- m_str = "fan_stopped";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4104;
							- m_transform = 0.0705882 0 0 0.220588 906 109 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  1096 1060  1096 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
						}
						{ CGIState 
							- _id = GUID 24741bcd-cc5e-419c-8a29-fdfc02008cd4;
							- m_type = 8;
							- m_pModelObject = { IHandle 
								- _m2Class = "IState";
								- _id = GUID cd53514a-f931-45c7-b5b7-977becb023c4;
							}
							- m_pParent = GUID 7c6c8a23-3037-410e-a357-eaf3e1d2abab;
							- m_name = { CGIText 
								- m_str = "fan_on";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 5;
							}
							- m_drawBehavior = 4104;
							- m_transform = 0.0705882 0 0 0.220588 915 612 ;
							- m_bIsPreferencesInitialized = 1;
							- m_AdditionalLabel = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 1;
							}
							- m_polygon = 4 0 0  0 1060  1096 1060  1096 0  ;
							- m_nNameFormat = 0;
							- m_nIsNameFormat = 0;
							- Compartments = { IRPYRawContainer 
								- size = 0;
							}
							- nAndLineCount = 0;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_pDefaultComponentRelation = ;
						}
						{ CGITrans 
							- _id = GUID 401e910f-d91f-46a3-9e52-d94e42ed9ba2;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 29;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 7ae3a071-ef70-4398-ab29-30e4562fe902;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID 7c6c8a23-3037-410e-a357-eaf3e1d2abab;
							- m_sourceType = 'F';
							- m_pTarget = GUID e6c8cfac-cc12-48b8-aea3-96be39526d6f;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 855 117 ;
							- m_TargetPort = 183 141 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID a7bf308c-7c54-409d-95af-c463cdc55605;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 5281803d-1311-4f53-84d1-3dd26e6c0204;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID e6c8cfac-cc12-48b8-aea3-96be39526d6f;
							- m_sourceType = 'F';
							- m_pTarget = GUID 24741bcd-cc5e-419c-8a29-fdfc02008cd4;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "start_fan/fanOn = true;                
fullSpeedOn = true;";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 891 795 ;
							- m_TargetPort = 982 601 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						{ CGITrans 
							- _id = GUID fef7e75c-94b2-4d96-9861-2a5bb963f34d;
							- _properties = { IPropertyContainer 
								- Subjects = { IRPYRawContainer 
									- size = 1;
									- value = 
									{ IPropertySubject 
										- _Name = "General";
										- Metaclasses = { IRPYRawContainer 
											- size = 1;
											- value = 
											{ IPropertyMetaclass 
												- _Name = "Graphics";
												- Properties = { IRPYRawContainer 
													- size = 1;
													- value = 
													{ IProperty 
														- _Name = "ShowLabels";
														- _Value = "False";
														- _Type = Bool;
													}
												}
											}
										}
									}
								}
							}
							- m_type = 28;
							- m_pModelObject = { IHandle 
								- _m2Class = "ITransition";
								- _id = GUID 8a357026-d555-4fa2-a50f-840083f56c8f;
							}
							- m_pParent = ;
							- m_name = { CGIText 
								- m_str = "";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 8;
							}
							- m_drawBehavior = 4096;
							- m_bIsPreferencesInitialized = 1;
							- m_pSource = GUID 24741bcd-cc5e-419c-8a29-fdfc02008cd4;
							- m_sourceType = 'F';
							- m_pTarget = GUID e6c8cfac-cc12-48b8-aea3-96be39526d6f;
							- m_targetType = 'T';
							- m_direction = ' ';
							- m_rpn = { CGIText 
								- m_str = "stop_fan/fanOn = false;";
								- m_style = "Arial" 10 0 0 0 1 ;
								- m_color = { IColor 
									- m_fgColor = 0;
									- m_bgColor = 0;
									- m_bgFlag = 0;
								}
								- m_position = 1 0 0  ;
								- m_nIdent = 0;
								- m_bImplicitSetRectPoints = 0;
								- m_nOrientationCtrlPt = 0;
							}
							- m_anglePoint1 = 0 0 ;
							- m_anglePoint2 = 0 0 ;
							- m_line_style = 1;
							- m_SourcePort = 217 406 ;
							- m_TargetPort = 171 848 ;
							- m_pInheritsFrom = { IHandle 
								- _m2Class = "";
							}
							- m_nInheritanceMask = 0;
							- m_bShowName = 1;
						}
						
						- m_access = 'Z';
						- m_modified = 'N';
						- m_fileVersion = "";
						- m_nModifyDate = 0;
						- m_nCreateDate = 0;
						- m_creator = "";
						- m_bScaleWithZoom = 1;
						- m_arrowStyle = 'S';
						- m_pRoot = GUID 377ba89a-e88a-42f2-9506-8f2b18b82eb6;
						- m_currentLeftTop = 0 0 ;
						- m_currentRightBottom = 0 0 ;
						- m_pInheritsFrom = { IHandle 
							- _m2Class = "";
						}
					}
				}
			}
		}
	}
	- _itsStateChart = { IHandle 
		- _m2Class = "IStateChart";
		- _id = GUID d28ac023-5269-474c-aaa6-a16fbcac3993;
	}
	- Associations = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IAssociationEnd 
			- _id = GUID 003d2dc1-e4b9-415f-a0cc-0ee0ab89f52d;
			- _myState = 8192;
			- _name = "parent";
			- _modifiedTimeWeak = 11.22.2013::2:0:56;
			- _multiplicity = "1";
			- _otherClass = { IClassifierHandle 
				- _m2Class = "IClass";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "";
				- _name = "Dispatcher";
				- _id = GUID 768ae538-24e4-40b1-8527-cf98dd09b2b1;
			}
			- _inverse = { IHandle 
				- _m2Class = "IPart";
				- _filename = "Default\\Default.sbs";
				- _subsystem = "Default";
				- _class = "Dispatcher";
				- _name = "itsTachometer";
				- _id = GUID eccc24f2-56c5-4bb4-8fa9-0823a0d3fca6;
			}
			- _linkName = "";
			- _linkType = Assoc;
			- _navigability = Navigable;
		}
	}
	- _classModifier = Unspecified;
}

