I-Logix-RPY-Archive version 8.8.0 Java 6107223
{ IClass 
	- _ownerHandle = { IHandle 
		- _m2Class = "ISubsystem";
		- _filename = "Default\\Default.sbs";
		- _subsystem = "";
		- _class = "";
		- _name = "Default";
		- _id = GUID dc273dcc-ec6a-4257-97c3-73c0831260b7;
	}
	- _id = GUID e1ddacfb-52fc-440d-b6b0-2864beed02cb;
	- _myState = 8192;
	- _name = "WaterTemperatureSensor";
	- _modifiedTimeWeak = 11.12.2013::16:20:4;
	- weakCGTime = 11.12.2013::16:20:4;
	- strongCGTime = 11.12.2013::10:31:53;
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

