I-Logix-RPY-Archive version 8.8.0 Java 6107223
{ IClass 
	- _ownerHandle = { IHandle 
		- _m2Class = "ISubsystem";
		- _filename = "Default.sbs";
		- _subsystem = "";
		- _class = "";
		- _name = "Default";
		- _id = GUID dc273dcc-ec6a-4257-97c3-73c0831260b7;
	}
	- _id = GUID ea9af8ef-52af-4c47-b928-8850e4eba154;
	- _myState = 8192;
	- _name = "Keyboard";
	- _modifiedTimeWeak = 11.12.2013::16:18:18;
	- weakCGTime = 11.12.2013::16:18:18;
	- strongCGTime = 11.12.2013::10:35:9;
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

