I-Logix-RPY-Archive version 8.8.0 Java 6107223
{ IClass 
	- _ownerHandle = { IHandle 
		- _m2Class = "ISubsystem";
		- _filename = "Default.sbs";
		- _subsystem = "";
		- _class = "";
		- _name = "Default";
		- _id = GUID dc273dcc-ec6a-4257-97c3-73c0831260b7;
	}
	- _id = GUID 4f561431-b6c3-4ba6-842e-24d9693d3050;
	- _myState = 8192;
	- _name = "Tachometer";
	- _modifiedTimeWeak = 11.12.2013::16:18:29;
	- weakCGTime = 11.12.2013::16:18:29;
	- strongCGTime = 11.12.2013::10:32:15;
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

